const User = require('../../../models/customerModel/userModel');

const getUser = async (req, res) => {
  const { id_user } = req.params;
  try {
    const user = await User.findById(id_user);
    if (!user) return res.status(404).json({ message: 'User no foundğŸ˜…' });
    return res.status(200).json({ message: 'User found', user });
  } catch (error) {
    console.log(error);
    return res.status(500).json({ message: 'Ups, there was a problem, please try againğŸ˜‘' });
  }
};

const updateStatus = async (req, res) => {
  const { id_user } = req.params;
  try {
    const user = await User.findById(id_user);
    if (!user) {
      return res.status(404).json({ message: 'User not foundğŸ˜¢' });
    }
    const update = user.status.includes('suspend')
      ? { $pull: { status: 'suspend' } }
      : { $push: { status: 'suspend' } };
    const updatedUser = await User.findOneAndUpdate({ _id: id_user }, update, { new: true });
    return res.status(201).json({
      message: `The user's status is: ${updatedUser.status.includes('suspend') ? 'suspend' : 'active'}`,
      user: updatedUser.roles,
    });
  } catch (error) {}
};

const getUsers = async (req, res) => {
  try {
    const users = await User.find();
    return res.status(200).json({ message: `${users.length === 0 ? 'There are not usersğŸ˜¢' : 'UsersğŸ¤©'}`, users });
  } catch (error) {
    console.log(error);
    return res.status(500).json({ message: 'Ups, there was a problem, please try againğŸ˜‘' });
  }
};

module.exports = {
  getUser,
  updateStatus,
  getUsers,
};
